services:
  # Banco de dados do Monolito Core (Django)
  postgres:
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Fila de mensagens assíncrona
  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672" # porta da fila
      - "15672:15672" # painel de administração
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Armazenamento de fotos (espelha o S3 localmente)
  minio:
    image: minio/minio
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API do MinIO
      - "9001:9001" # painel de administração
    volumes:
      - minio_data:/data

  core:
    build:
      context: ./services/core
      target: development
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8000:8000"
    depends_on:
        postgres:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
    volumes:
      - ./services/core:/app
      - ./infra:/app/infra

  core-consumer:
    build:
      context: ./services/core
      target: development
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
    command: python manage.py consume_queue
    depends_on:
        postgres:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
    volumes:
      - ./services/core:/app
      - ./infra:/app/infra

volumes:
  postgres_data:
  rabbitmq_data:
  minio_data:
