# Generated by Django 6.0.4 on 2026-06-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('usuario_email', models.CharField(blank=True, max_length=255, null=True)),
                ('operacao', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SELECT', 'Select')], max_length=10)),
                ('tabela', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dados_antes', models.JSONField(blank=True, null=True)),
                ('dados_depois', models.JSONField(blank=True, null=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_log_timestamp_idx'), models.Index(fields=['usuario_id'], name='audit_log_usuario_id_idx'), models.Index(fields=['tabela'], name='audit_log_tabela_idx')],
            },
        ),
    ]
