# Generated by Django 6.0.4 on 2026-07-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('uf', models.CharField(help_text='Sigla do estado (UF)', max_length=2)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('morador', 'Morador'), ('gestor', 'Gestor'), ('gerente_geral', 'Gerente Geral')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.ForeignKey(blank=True, help_text='Obrigatória para gestor e supervisor; gerente_geral e morador não têm cidade própria.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='accounts.cidade'),
        ),
    ]
