# Generated by Django 6.0.4 on 2026-06-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='matricula',
        ),
    ]
