# Generated by Django 6.0.6 on 2026-07-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_email_confirmado_usuario_token_confirmacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cadastro_completo',
            field=models.BooleanField(default=True, help_text='False apenas para moradores que se cadastraram via Google e ainda não preencheram o formulário complementar.'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
