# Generated by Django 6.0.4 on 2026-05-19 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_microservico', models.CharField(help_text='ID gerado pelo microserviço (MongoDB)', max_length=50, unique=True)),
                ('pontuacao', models.DecimalField(decimal_places=2, default=0, help_text='Pontuação já calculada recebida do microserviço', max_digits=8)),
                ('data_hora_coleta', models.DateTimeField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='program.imovel')),
            ],
            options={
                'ordering': ['-id_microservico'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('arquivo_url', models.URLField(help_text='URL do objeto no S3/MinIO')),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('enviada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_enviadas', to=settings.AUTH_USER_MODEL)),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='collection.registrocoleta')),
            ],
            options={
                'ordering': ['-enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='Contestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em análise'), ('aceita', 'Aceita'), ('negada', 'Negada')], default='aberta', max_length=20)),
                ('resposta', models.TextField(blank=True)),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('aberta_por', models.ForeignKey(limit_choices_to={'perfil': 'morador'}, on_delete=django.db.models.deletion.PROTECT, related_name='contestacoes_abertas', to=settings.AUTH_USER_MODEL)),
                ('analisada_por', models.ForeignKey(blank=True, limit_choices_to={'perfil': 'gestor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestacoes_analisadas', to=settings.AUTH_USER_MODEL)),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contestacoes', to='collection.registrocoleta')),
            ],
            options={
                'ordering': ['-aberta_em'],
            },
        ),
    ]
