# Generated by Django 6.0.4 on 2026-06-13 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('program', '0002_alter_saldopontos_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocoleta',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='program.programa'),
        ),
        migrations.AlterField(
            model_name='registrocoleta',
            name='pontuacao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pontuação calculada no core: peso_kg × ConstantePontuacao.pontos_por_kg', max_digits=8),
        ),
    ]
