# Generated by Django 6.0.4 on 2026-07-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('program', '0003_ciclo_alter_consolidacao_ciclo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocoleta',
            name='ciclo_consolidado',
            field=models.ForeignKey(blank=True, help_text='Ciclo no qual esta coleta foi convertida em benefícios', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas_consolidadas', to='program.ciclo'),
        ),
    ]
