# Generated by Django 6.0.4 on 2026-05-19 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocoleta',
            name='material',
        ),
    ]
