# Generated by Django 6.0.4 on 2026-07-10 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_registrocoleta_ciclo_consolidado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocoleta',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário (Gestor/Supervisor) que registrou a coleta manualmente. Nulo se veio do app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas_registradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
