# Generated by Django 6.0.4 on 2026-06-05 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_registrocoleta_material'),
        ('program', '0004_remove_imovel_latitude_remove_imovel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocoleta',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='program.programa'),
        ),
        migrations.AlterField(
            model_name='registrocoleta',
            name='pontuacao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pontuação calculada no core: peso_kg × ConstantePontuacao.pontos_por_kg', max_digits=8),
        ),
    ]
