# Generated by Django 6.0.4 on 2026-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_registrocoleta_ciclo_consolidado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocoleta',
            name='id_microservico',
            field=models.CharField(blank=True, help_text='ID gerado pelo microserviço (MongoDB). Nulo para coletas manuais.', max_length=50, null=True, unique=True),
        ),
    ]
