# Generated by Django 6.0.4 on 2026-07-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_registrocoleta_registrado_por'),
        ('collection', '0003_tornar_id_microservico_optional'),
    ]

    operations = [
    ]
