# Generated by Django 6.0.4 on 2026-05-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_microservico', models.CharField(help_text='ID gerado pelo microserviço (MongoDB)', max_length=50, unique=True)),
                ('inscricao_imobiliaria', models.CharField(max_length=50)),
                ('pontuacao', models.DecimalField(decimal_places=2, default=0, help_text='Pontuação já calculada recebida do microserviço', max_digits=8)),
                ('data_hora_coleta', models.DateTimeField()),
                ('data_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='program.imovel')),
            ],
            options={
                'ordering': ['-data_hora_coleta'],
            },
        ),
    ]
