# Generated by Django 6.0.4 on 2026-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocoleta',
            name='pontos_gerados',
        ),
        migrations.AddField(
            model_name='registrocoleta',
            name='desconto_gerado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pontos percentuais de desconto no IPTU gerados', max_digits=5),
        ),
        migrations.AlterField(
            model_name='registrocoleta',
            name='material',
            field=models.CharField(choices=[('papel', 'Papel/Papelão'), ('plastico', 'Plástico'), ('aluminio', 'Alumínio'), ('vidro', 'Vidro'), ('metal', 'Metal'), ('eletronico', 'Eletrônico')], max_length=20),
        ),
    ]
