# Generated by Django 6.0.4 on 2026-05-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_registrocoleta_pontos_gerados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocoleta',
            name='agente_id',
        ),
        migrations.RemoveField(
            model_name='registrocoleta',
            name='desconto_gerado',
        ),
        migrations.RemoveField(
            model_name='registrocoleta',
            name='material',
        ),
        migrations.RemoveField(
            model_name='registrocoleta',
            name='peso_kg',
        ),
        migrations.AddField(
            model_name='registrocoleta',
            name='pontuacao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pontuação já calculada recebida do microserviço', max_digits=8),
        ),
    ]
