# Generated by Django 6.0.4 on 2026-05-11 12:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao', models.CharField(max_length=50, unique=True)),
                ('cep', models.CharField(help_text='Formato: XXXXX-XXX', max_length=9)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(help_text='Sigla do estado (UF)', max_length=2)),
                ('num_moradores', models.PositiveIntegerField(default=1, help_text='Quantidade de moradores na residência', validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('data_adesao', models.DateField(auto_now_add=True)),
                ('titular', models.ForeignKey(limit_choices_to={'perfil': 'morador'}, on_delete=django.db.models.deletion.PROTECT, related_name='imoveis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaldoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(help_text='Mês de apuração (MM-YYYY)', max_length=7)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Desconto acumulado no IPTU (%)', max_digits=5)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='program.imovel')),
            ],
            options={
                'unique_together': {('imovel', 'ciclo')},
            },
        ),
    ]
