# Generated by Django 6.0.4 on 2026-05-19 14:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('desconto_maximo', models.DecimalField(decimal_places=2, default=40.0, help_text='Teto de desconto no IPTU por ciclo (em %)', max_digits=5)),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao', models.CharField(max_length=50, unique=True)),
                ('cep', models.CharField(help_text='Formato: XXXXX-XXX', max_length=9)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(help_text='Sigla do estado (UF)', max_length=2)),
                ('num_moradores', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('data_adesao', models.DateField(auto_now_add=True)),
                ('moradores', models.ManyToManyField(blank=True, help_text='Demais usuários (moradores) vinculados ao imóvel', related_name='imoveis_vinculados', to=settings.AUTH_USER_MODEL)),
                ('titular', models.ForeignKey(limit_choices_to={'perfil': 'morador'}, on_delete=django.db.models.deletion.PROTECT, related_name='imoveis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consolidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executada_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('falhou', 'Falhou')], default='pendente', max_length=20)),
                ('total_imoveis', models.PositiveIntegerField(default=0)),
                ('total_pontos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('executada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidacoes_executadas', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidacoes', to='program.programa')),
            ],
            options={
                'ordering': ['-executada_em'],
            },
        ),
        migrations.CreateModel(
            name='RegraPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_por_real', models.DecimalField(decimal_places=2, default=10.0, help_text='Quantos pontos equivalem a 1% de desconto', max_digits=6)),
                ('minimo_para_beneficio', models.PositiveIntegerField(default=100, help_text='Pontuação mínima para gerar qualquer benefício')),
                ('permite_acumulo_ciclos', models.BooleanField(default=False)),
                ('programa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='program.programa')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(help_text='Mês de apuração (MM-YYYY)', max_length=7)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Desconto acumulado no IPTU (%)', max_digits=5)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='program.imovel')),
            ],
            options={
                'unique_together': {('imovel', 'ciclo')},
            },
        ),
    ]
