# Generated by Django 6.0.4 on 2026-07-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidacao',
            name='ciclo',
            field=models.CharField(blank=True, help_text='Mês de apuração (MM-YYYY)', max_length=7),
        ),
    ]
