# Generated by Django 6.0.4 on 2026-07-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_consolidacao_ciclo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: 1º Semestre 2026, Maio/2026', max_length=100)),
                ('tipo', models.CharField(choices=[('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], default='mensal', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='program.programa')),
            ],
            options={
                'ordering': ['-data_inicio'],
                'unique_together': {('programa', 'nome')},
            },
        ),
        migrations.AlterField(
            model_name='consolidacao',
            name='ciclo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consolidacoes', to='program.ciclo'),
        ),
        migrations.AlterField(
            model_name='saldopontos',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='program.ciclo'),
        ),
    ]
