# Generated by Django 6.0.4 on 2026-06-05 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_delete_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saldopontos',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='imovel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='saldopontos',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='program.programa'),
        ),
        migrations.AlterUniqueTogether(
            name='saldopontos',
            unique_together={('imovel', 'programa', 'ciclo')},
        ),
        migrations.CreateModel(
            name='ConstantePontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_por_kg', models.DecimalField(decimal_places=4, default='1.5000', help_text='Pontos gerados por kg coletado (peso × constante = pontuação)', max_digits=8)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constantes_pontuacao_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'constante de pontuação',
                'verbose_name_plural': 'constante de pontuação',
            },
        ),
    ]
