# Generated by Django 6.0.4 on 2026-06-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_saldopontos_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='geocodificacao_falhou',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='longitude',
        ),
    ]
