# Generated by Django 6.0.4 on 2026-06-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_remove_imovel_geocodificacao_falhou_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='geocodificacao_falhou',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
