# Generated by Django 6.0.4 on 2026-06-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_add_lat_lon_to_imovel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='longitude',
        ),
    ]
