# Generated by Django 6.0.4 on 2026-06-23 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0002_alter_saldopontos_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('participacao', 'Participação'), ('impacto', 'Impacto'), ('ranking', 'Ranking'), ('auditoria', 'Auditoria')], max_length=20)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('relatorio', models.TextField()),
                ('tokens_utilizados', models.PositiveIntegerField(default=0)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('gerado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_llm_gerados', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_llm', to='program.programa')),
            ],
            options={
                'ordering': ['-gerado_em'],
            },
        ),
    ]
