# Generated by Django 6.0.4 on 2026-04-27 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao', models.CharField(max_length=50, unique=True)),
                ('cpf_titular', models.CharField(max_length=14)),
                ('nome_titular', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('data_adesao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabelaPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField(help_text='Ano de apuração')),
                ('material', models.CharField(choices=[('papel', 'Papel/Papelão'), ('plastico', 'Plástico'), ('vidro', 'Vidro'), ('metal', 'Metal'), ('eletronico', 'Eletrônico')], max_length=20)),
                ('pontos_por_kg', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'unique_together': {('ciclo', 'material')},
            },
        ),
        migrations.CreateModel(
            name='SaldoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField()),
                ('total_pontos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='program.imovel')),
            ],
            options={
                'unique_together': {('imovel', 'ciclo')},
            },
        ),
    ]
