# Generated by Django 6.0.4 on 2026-04-27 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TabelaPontuacao',
        ),
        migrations.RemoveField(
            model_name='saldopontos',
            name='total_pontos',
        ),
        migrations.AddField(
            model_name='imovel',
            name='num_moradores',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade de moradores na residência', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='saldopontos',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto acumulado no IPTU (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='saldopontos',
            name='total_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso total de material entregue no ciclo (kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saldopontos',
            name='ciclo',
            field=models.IntegerField(help_text='Ano de apuração'),
        ),
    ]
