# Generated by Django 6.0.4 on 2026-05-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_delete_tabelapontuacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldopontos',
            name='total_kg',
        ),
    ]
